# Generated by Django 2.2.16 on 2020-10-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='uhmmmm',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
